server:
  port: 8003
spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://123.56.164.214:3306/user_center
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver